baseURL = 'https://junegunn.github.io/'
languageCode = 'en-us'
title = 'junegunn.choi.'

theme = ['hugo-notice', 'hugo-book']
enableEmoji = true
enableRobotsTXT = true
enableGitInfo = true

# No tags and categories
disableKinds = ["taxonomy"]

[params]
  # BookTheme = 'auto'
  # BookLogo = 'logo.png'
  BookSearch = true
  BookFavicon = 'favicon.ico'

  [params.author]
    name = 'Junegunn Choi'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions.extras.mark]
      enable = true

    # [markup.goldmark.renderer]
    #   unsafe = true

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'emacs'
    tabWidth = 4

[permalinks]
  [permalinks.page]
    docs = '/:sections[1:]/:slug/'
